name: Patient Portal Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run PyTest (Chrome headless)
        env:
          BASE_URL: https://demo.openemr.io/openemr/portal/index.php
          PATIENT_USERNAME: Phil1
          PATIENT_PASSWORD: phil
          PATIENT_EMAIL: heya@invalid.email.com
          HEADLESS: "true"
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --browser=chrome \
                 --html=reports/report_chrome.html \
                 --self-contained-html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-chrome
          path: reports/
